settings:
  name: Azure NetApp Files
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: All Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Azure NetApp Files docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Azure NetApp Files
          url: /concept-azure-netapp-files.html
        - title: Quick start
          url: /task-quick-start.html
        - title: Set up an Azure AD application
          url: /task-set-up-azure-ad.html
        - title: Create a working environment
          url: /task-create-working-env.html
    - title: Use Azure NetApp Files
      entries:
        - title: Create and mount volumes
          url: /task-create-volumes.html
        - title: Manage existing volumes
          url: /task-manage-volumes.html
        - title: Remove Azure NetApp Files
          url: /task-remove-working-env.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about Azure NetApp Files
          url: concept-azure-netapp-files.html
        - title: Quick start
          url: task-quick-start.html
    - title: Use Azure NetApp Files
      links:
        - title: Create volumes
          url: task-create-volumes.html
        - title: Manage volumes
          url: task-manage-volumes.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events

